---
title: "Predicting Movie Success"
author: "Carlone Scott"
date: "14/08/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

### Load Requied packages and Read in data 

```{r warning = FALSE, results="hide", message=FALSE}
library(plotly)
library(dplyr)
library(readxl)
library(tidyverse)
library(caret)

Movies_raw <- read_xlsx("Bechdel.xlsx", col_names = TRUE)
Movies_test <- read_csv("test.csv", col_names = TRUE)

```

### Data cleaning

```{r clean, warning = FALSE, echo=TRUE}

Movies <- Movies_raw
names(Movies) <- c("year", "imdb", "budget", "domgross", "intgross", "code","budget_2013", "domgross_2013",
                   "intgross_2013", "Test")

#str(Movies)
Movies <- as.data.frame(Movies[-1, -c(11, 12)])

Movies_num <- Movies[, -2]

func <- function(x){
  as.numeric(gsub("PASS", 1, gsub("FAIL", 0, x)))
}

Movies_num <- as.data.frame(lapply(Movies_num, FUN = func))

str(Movies)

#mdata <- melt(Movies, id=c("year"))

#Remove id column
Mov_code <- Movies[,2]
#Movies %>% modify_at(c(1,3:7,8), as.numeric)

# Remove NA from data set
Movies_num <- Movies_num[complete.cases(Movies_num), ]

# Add provit variable gross less budget (assuming the budget = real cost to produce movies)
Movies_num$domProfit <- Movies_num$domgross - Movies_num$budget
Movies_num$intProfit <- Movies_num$intgross - Movies_num$budget
Movies_num$domProfit_2013 <- Movies_num$domgross_2013 - Movies_num$budget_2013
Movies_num$intProfit_2013 <- Movies_num$intgross_2013 - Movies_num$budget_2013

# Reorder columns and remove NA
Movies_num <- Movies_num[ ,c(1, 2, 3, 4, 10, 11, 6, 7, 8, 12, 13, 9)]

# Remove NA from data set
Movies_clean <- Movies_num[complete.cases(Movies_num), ]

summary(Movies_clean)

#plot_ly(Movies, x = ~`Dom gross`, y = ~Year, type = 'scatter', mode = 'lines')
#View(Movies)
```


### Data Analysis


```{r warning = FALSE, echo=TRUE}

# Look at the distribution of the data 
hist_l = list()
#Movies_quant <- as.data.frame(Movies[,-c(2,6)])
hist_p <- function(df){
  for(i in 1:10){
    hist_l[i] <- plot_ly(x = df[ ,i], type = "histogram", name = names(df)[i]) 
  }
  return(hist_l)
}


hist_pl <- hist_p(Movies_clean)

unadjusted <- subplot(hist_pl[[2]], hist_pl[[3]], hist_pl[[4]], hist_pl[[5]], hist_pl[[1]], nrows = 4, margin = 0.04, 
                      heights = c(0.25, 0.25, 0.25, 0.25))
adjusted <- subplot(hist_pl[[7]], hist_pl[[8]], hist_pl[[9]], nrows = 3, margin = 0.04, heights = c(0.33, 0.33, 0.33))
#year
unadjusted
adjusted

```


### Analyis part 2

```{r warning = FALSE, message=FALSE}

# Look at the distribution of the data 
box_l <- list()

box_p <- function(df){
  for(i in 1:11){
    box_l[i] <- plot_ly(y = df[,i], type = "box", name = names(df)[i])
  }
  return(box_l)
}

str(Movies_clean)
box_pl <- box_p(Movies_clean)

subplot(box_pl[[2]], box_pl[[3]], box_pl[[4]], box_pl[[5]], box_pl[[6]])
subplot(box_pl[[7]], box_pl[[8]], box_pl[[9]], box_pl[[10]], box_pl[[11]])

# Percent of movies that passed test all time
percent_pass <- sum(Movies_num$Test)/length(Movies$Test) * 100

Movies_order <- Movies_clean[order(Movies_clean$year),]
Movies_order <- Movies_order[, c(1, 12)]

sum_yr <- aggregate(Movies_order$Test, by=list(Year = Movies_order$year), FUN = sum)
sum_yr$Pass <- sum_yr$x

library(plyr)
freq <- count(Movies_order, "year")

Change_percent <- cbind(sum_yr, `Percent pass Berchdel test` = (sum_yr$x/freq$freq)*100)

succes_time <- plot_ly(sum_yr, x = ~Year, y = ~Pass,
                       type = "scatter", mode = "markers+lines") 

percent_time <- plot_ly(Change_percent, x = ~Year, y = ~`Percent pass Berchdel test`, 
                        type = "scatter", mode = "markers+lines") 

subplot(percent_time, succes_time, nrows = 2)

```

Bassed on the binary definition `r percent_pass` $\%$ of movies passed the test. 

### Data Prediction

```{r prediction, warning = FALSE, echo=TRUE, message=FALSE}

Movies_clean$Test <- factor(Movies_clean$Test, levels = c(0, 1))

str(Movies_clean)
table(Movies_clean$Test)

# Prep Training and Test data.
set.seed(50)
split_Movies <- createDataPartition(Movies_clean$Test, p=0.85, list = F) 
train <- Movies_clean[split_Movies, ]
test_split <- Movies_clean[-split_Movies, ]

table(train$Test)

set.seed(50)
scale_train_down <- downSample(x = train[, 2:11], y = train$Test, list = FALSE, yname = "Test")

table(scale_train_down$Test)

set.seed(50)
scale_train_up <- upSample(x = train[, 2:11], y = train$Test, list = FALSE, yname = "Test")
table(scale_train_up$Test)

# Look at different models 

Movies_glm <- glm(Test ~ budget + domgross + intgross + domProfit + intProfit 
                    + budget_2013 + domgross_2013 + intgross_2013 + domProfit_2013
                    + intProfit_2013, data = scale_train_up, family = binomial)

Movies_glm_2 <- glm(Test ~ budget + domgross + intgross
                    + budget_2013 + domgross_2013 + intgross_2013, 
                    data = scale_train_up, family = binomial)

Movies_glm_1 <- glm(Test ~ budget + domgross +  budget_2013 + domgross_2013, 
                    data = scale_train_up, family = binomial)

summary(Movies_glm)
summary(Movies_glm_1)
summary(Movies_glm_2) #Best model so far

# Prediction using model
pred <- predict(Movies_glm_2, newdata = test_split, type = "response")

pred_test <- ifelse(pred > 0.5, 1, 0)
Test_pred <- factor(pred_test, levels=c(0, 1))
Test_act <- factor(test_split$Test)
mean(Test_pred == Test_act)

# Predict test.csv data
Movies_test <- read_csv("test.csv", col_names = TRUE)

pred_N <- predict(Movies_glm_2, newdata = Movies_test, type = "response")
pred_test_csv <- ifelse(pred_N > 0.5, 1, 0)
Test_pred_csv <- factor(pred_test_csv, levels=c(0, 1))


Movies_New <- as.data.frame(cbind(Movies_test, Test_pred_csv))

func <- function(x){
  gsub(1, "PASS", gsub(0, "FAIL", x))
}

Movies_Pred <- as.data.frame(lapply(Movies_New$Test_pred_csv, FUN = func))
head(Movies_New)
save(x = Movies_Pred, file = "Movies_Pred.csv")

```
